// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button'];
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox'];
    AInput: typeof import('ant-design-vue/es')['Input'];
  }
}

export {};
